enum ProductCategory {
  Electronics = 'Электроника',
  Clothing = 'Одежда',
  Books = 'Книги',
  HomeAndGarden = 'Дом и сад',
  Beauty = 'Красота',
  Toys = 'Игрушки',
  SportsAndOutdoors = 'Спорт и активный отдых',
  FoodAndGrocery = 'Продукты и бакалея',
  Health = 'Здоровье',
  Automotive = 'Автомобильные товары',
  Music = 'Музыка',
  Movies = 'Фильмы',
  PetSupplies = 'Товары для животных',
  OfficeSupplies = 'Канцелярские товары',
  Jewelry = 'Украшения',
  Furniture = 'Мебель',
  Miscellaneous = 'Разное',
}

const productCategories = {
  Electronics: {
    Smartphones: 'Смартфоны',
    LaptopsAndPCs: 'Ноутбуки и ПК',
    Televisions: 'Телевизоры',
    CamerasAndPhotography: 'Камеры и фотоаппараты',
    ElectronicsAccessories: 'Аксессуары для электроники',
  },
  Clothing: {
    MensClothing: 'Мужская одежда',
    WomensClothing: 'Женская одежда',
    ChildrensClothing: 'Детская одежда',
    Footwear: 'Обувь',
    ClothingAccessories: 'Аксессуары к одежде',
  },
  Books: {
    Fiction: 'Художественная литература',
    NonFiction: 'Научно-популярные книги',
    ChildrensBooks: 'Детские книги',
    Textbooks: 'Учебники',
    Audiobooks: 'Аудиокниги',
  },
  HomeAndGarden: {
    Furniture: 'Мебель',
    DecorAndInterior: 'Декор и предметы интерьера',
    Appliances: 'Бытовая техника',
    GardeningAndOutdoor: 'Садоводство и садовые товары',
    Kitchenware: 'Кухонные товары',
  },
  Beauty: {
    FaceCare: 'Косметика для лица',
    Fragrances: 'Парфюмерия и ароматы',
    HairCare: 'Уход за волосами',
    BodyCare: 'Уход за телом',
    BeautyAccessories: 'Украшения и аксессуары для красоты',
  },
  Toys: {
    ChildrensToys: 'Детские игрушки',
    BuildingBlocksAndPuzzles: 'Конструкторы и пазлы',
    GamesAndPuzzles: 'Игры и головоломки',
    DollsAndAccessories: 'Куклы и аксессуары',
    EducationalToys: 'Развивающие игрушки',
  },
  SportsAndOutdoors: {
    SportsEquipment: 'Спортивные товары',
    OutdoorRecreation: 'Активный отдых на природе',
    FitnessAndTraining: 'Фитнес и тренировки',
    WaterSports: 'Водные виды спорта',
    WinterSports: 'Зимние виды спорта',
  },
  FoodAndGrocery: {
    Groceries: 'Продукты питания',
    Beverages: 'Напитки',
    SweetsAndSnacks: 'Кондитерские изделия',
    HealthFood: 'Здоровое питание',
    CookingIngredients: 'Кулинарные ингредиенты',
  },
  Health: {
    VitaminsAndSupplements: 'Витамины и добавки',
    MedicalSupplies: 'Медицинские товары',
    HealthAndBeauty: 'Уход за здоровьем и красотой',
    MedicalEquipment: 'Медицинская техника',
    FitnessAndWellness: 'Товары для фитнеса и здорового образа жизни',
  },
  Automotive: {
    PartsAndAccessories: 'Запчасти и аксессуары',
    OilsAndFluids: 'Масла и жидкости',
    ToolsAndEquipment: 'Инструменты и оборудование',
    CarElectronics: 'Автомобильные электроники',
    TiresAndWheels: 'Шины и диски',
  },
  PetSupplies: {
    FoodAndTreats: 'Корм и лакомства',
    LeashesAndCollars: 'Поводки и ошейники',
    PetToys: 'Игрушки для животных',
    GroomingAndHygiene: 'Уход и гигиена',
    AquariumAndTerrarium: 'Аквариум и террариум',
  },
  OfficeSupplies: {
    PensAndPencils: 'Ручки и карандаши',
    PaperProducts: 'Бумажные товары',
    FoldersAndOrganizers: 'Папки и органайзеры',
    OfficeAccessories: 'Канцелярские принадлежности',
    PrintersAndSupplies: 'Принтеры и расходные материалы',
  },
  Jewelry: {
    Rings: 'Кольца',
    ChainsAndNecklaces: 'Цепи и ожерелья',
    Earrings: 'Серьги',
    Bracelets: 'Браслеты',
    Watches: 'Часы',
  },
  Furniture: {
    BedroomFurniture: 'Мебель для спальни',
    LivingRoomFurniture: 'Мебель для гостиной',
    DiningRoomFurniture: 'Мебель для столовой',
    HomeOfficeFurniture: 'Мебель для домашнего офиса',
    OutdoorFurniture: 'Мебель для улицы и сада',
  },
}
